import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

/**
 * IMPORTANT: This Supabase client is ONLY used for token verification purposes.
 * It does NOT access Supabase database or storage.
 * All data operations are performed with SQLite database.
 * 
 * This client's sole purpose is to verify JWT tokens generated by Supabase Auth.
 */

const supabaseUrl =
  process.env.SUPABASE_URL ||
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  process.env.GATED_SUPABASE_URL;
const supabaseServiceKey =
  process.env.SUPABASE_SERVICE_ROLE_KEY ||
  process.env.GATED_SUPABASE_SERVICE_ROLE_KEY;
const supabaseAnonKey =
  process.env.SUPABASE_ANON_KEY ||
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// Prefer anon/publishable key for auth.getUser(). It is sufficient for token
// verification and avoids failures from stale/rotated service-role keys.
const supabaseKey = supabaseAnonKey || supabaseServiceKey;

if (!supabaseUrl || !supabaseKey) {
  throw new Error('Missing SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) and Supabase auth key');
}

// Log which key type we're using for debugging
if (supabaseAnonKey) {
  console.log('✅ Using Supabase anon key for token verification');
} else if (supabaseServiceKey) {
  console.log('⚠️  Using Supabase service role key for token verification fallback');
} else {
  console.warn('❌ No valid Supabase key found! Authentication will not work.');
}

// Create minimal Supabase client only for auth token verification
const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
});

// Export only the minimal client needed for auth verification
export default supabase;